name: PotatoIpDisplay
main: indi.nightfish.potato_ip_display.PotatoIpDisplay
version: ${pluginVersion}
authors: ["NightFish", "yukonisen"]
softdepend: [PlaceholderAPI]
api-version: 1.13

# commands:
#  potatoipdisplay:
#    description: Main command of PotatoIpDisplay.
#    aliases:
#      - pipd
#    usage: /potatoipdisplay