name: PotatoIpDisplay
main: indi.nightfish.potato_ip_display.PotatoIpDisplay
version: ${pluginVersion}
authors: ["NightFish", "yukonisen"]
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
 potatoipdisplay:
    description: Main command of PotatoIpDisplay.
    aliases:
      - pipd
    usage: /potatoipdisplay

permissions:
  potatoipdisplay.*:
    description: "Maximum permissions for PotatoIPDisplay."
    default: op
    children:
      - potatoipdisplay.reload
      - potatoipdisplay.lookup
      - potatoipdisplay.command
  potatoipdisplay.command:
    description: "Run PotatoIPDisplay commands"
    default: op
  potatoipdisplay.lookup:
    description: "Look up the attribution info of any player or IP"
    default: op
  potatoipdisplay.reload:
    description: "Reload PotatoIPDisplay"
    default: op